- name: "Create Directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ tmp_prefix }}"

- shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: Downloading RVM
  get_url:
    url: https://get.rvm.io
    dest: "{{ tmp_prefix }}/rvm-installer.sh"

- name: Installing RVM
  shell: "cat {{ tmp_prefix }}/rvm-installer.sh | bash -s stable"

- name: Installing Ruby
  shell: source /etc/profile.d/rvm.sh && rvm install {{ ruby_version }}

- file:
    path: "{{ tmp_prefix }}"
    state: absent
